all:	shell serial parallel

shell:	shell.cpp
	g++ shell.cpp -o shell

serial:	serial.cpp
	g++ serial.cpp -o serial

parallel:	 parallel.cpp
	g++ parallel.cpp -o parallel

clean:
	rm -rf shell serial parallel *.jpeg* *.jpg* *.png*
